services:
  - type: web
    name: ffmpeg-reels-generator
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:5000 app:app --timeout 300
    envVars:
      - key: PORT
        value: 5000
    staticPublishPath: static

